# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Drink-O-Matic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Drink-O-Matic

  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SDWebImage', '~> 5.0'
  
  target 'Drink-O-MaticTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Drink-O-MaticUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
